/**
 * Phase 8: per-MonitoredUrl "topic card" — the user-facing summary of what
 * each sub-page covers, generated by the LLM at site-bootstrap time and
 * refreshed when the page changes meaningfully.
 *
 * The topic card replaces user-facing CSS selectors and strip patterns:
 * the user sees a card describing what info this page contains, plus a
 * polling cadence picker. Selectors and patterns are inferred behind the
 * scenes (and stored on the MonitoredUrl row) so we can keep the existing
 * extract/diff pipeline untouched.
 */
import { z } from "zod";
import { openai, MODELS, parseJsonSafe } from "@/lib/openai";
import { ChangeCategory } from "@/generated/prisma/enums";

/** Categories shown to the user. Mirrors ChangeCategory but with a
 *  human-friendly name and an optional polling-cadence default. */
export const TOPIC_CATEGORIES = [
  "POLICY",
  "FEES",
  "APPOINTMENTS",
  "DOCUMENTS",
  "NEWS",
  "OTHER",
  "SKIP",
] as const;
export type TopicCategory = (typeof TOPIC_CATEGORIES)[number];

/** Sane per-category polling defaults. Appointments change minutely;
 *  policy text changes daily at most. Easy to override per-URL in the UI. */
export const CATEGORY_POLL_DEFAULTS: Record<TopicCategory, number> = {
  APPOINTMENTS: 30,
  NEWS: 120,
  FEES: 720,
  POLICY: 720,
  DOCUMENTS: 720,
  OTHER: 360,
  SKIP: 1440,
};

/** Map a TopicCategory back to a DB ChangeCategory for classification. */
export function topicToChangeCategory(t: TopicCategory): ChangeCategory {
  switch (t) {
    case "POLICY":
      return ChangeCategory.POLICY_CHANGE;
    case "FEES":
      return ChangeCategory.FEE_CHANGE;
    case "APPOINTMENTS":
      return ChangeCategory.APPOINTMENT;
    case "DOCUMENTS":
      return ChangeCategory.DOCUMENT_REQUIREMENT;
    default:
      return ChangeCategory.UNKNOWN;
  }
}

/** What the LLM returns when classifying a sub-page. */
const TopicCardSchema = z.object({
  title: z.string().min(1).max(140),
  /** 1-2 sentence plain-English summary of what info this page contains. */
  summary: z.string().min(1).max(400),
  /** SKIP means "drop this page; not visa-relevant" (e.g. /privacy-policy/). */
  category: z.enum(TOPIC_CATEGORIES),
  /** Notable fields the user should be alerted about if they change.
   *  E.g. ["Tourist visa fee USD", "Processing time (days)"]. Free-form. */
  importantFields: z.array(z.string().min(1).max(140)).max(8).default([]),
  /** Optional CSS selector hint. The bootstrap path uses this to refine
   *  MonitoredUrl.contentSelector (else falls back to "main" / "body"). */
  contentSelector: z.string().max(200).nullable().default(null),
});
export type TopicCard = z.infer<typeof TopicCardSchema>;

/** What gets stored on MonitoredUrl.topicCard (jsonb). */
export interface StoredTopicCard extends TopicCard {
  /** Updated by the poll pipeline when a change is detected. Renders as a
   *  badge + diff preview in the dashboard card grid. */
  lastChangeNote?: string | null;
  lastChangeAt?: string | null;
}

const SYSTEM_PROMPT = `You analyse a single page from a visa / embassy / immigration website.
Given the page text, decide:
  1) Is this page interesting to a visa applicant tracking changes?
     (Skip privacy notices, login pages, search forms, sitemaps, careers, blog
      indexes that don't list news, error pages, language switchers.)
  2) If yes, classify into ONE category:
       POLICY        — visa rules, eligibility, restrictions
       FEES          — visa application fees, payment info, charges
       APPOINTMENTS  — booking systems, slot availability, appointment forms
       DOCUMENTS     — required documents, forms, photo specs, supporting materials
       NEWS          — announcements, news listings, alerts
       OTHER         — visa-relevant but doesn't fit above (only when truly other)
       SKIP          — not visa-relevant; drop this page
  3) Write a SHORT title (≤80 chars) — the kind of thing a user wants on a card.
  4) Write a 1-2 sentence summary of what info the page contains.
  5) List 1-6 "importantFields" — concrete things on this page a user would
     want to be alerted about if they changed (e.g. "Tourist visa fee USD",
     "Document checklist", "Processing time"). Skip generic things like
     "page navigation" or "site footer".
  6) Optionally suggest a CSS selector that scopes monitoring to the meaningful
     content area (e.g. "main", ".content-area", "#visa-news"). Null if unsure.

Return JSON: { title, summary, category, importantFields, contentSelector }`;

/** Generate a topic card for a single page. Retries up to MAX_ATTEMPTS times
 *  on transient errors (503, 429, network) with exponential backoff before
 *  giving up and throwing. */
const MAX_ATTEMPTS = 3;

function shouldRetry(err: unknown): boolean {
  // OpenAI SDK error has `status` field for HTTP errors. We retry on 5xx,
  // 429 (rate limit), and any non-API error (network).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const e = err as any;
  const status: number | undefined = e?.status ?? e?.response?.status;
  if (typeof status === "number") {
    return status >= 500 || status === 429;
  }
  return true;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export async function generateTopicCard(
  pageUrl: string,
  pageTitle: string,
  pageText: string
): Promise<TopicCard> {
  const truncated = pageText.slice(0, 14_000);
  const userBlock = [
    `URL: ${pageUrl}`,
    `Page title: ${pageTitle}`,
    "",
    "Page text:",
    truncated,
  ].join("\n");

  let lastErr: unknown;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const res = await openai.chat.completions.create({
        model: MODELS.fast,
        response_format: { type: "json_object" },
        temperature: 0.2,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userBlock },
        ],
      });
      const raw = parseJsonSafe(res.choices[0].message.content);
      return TopicCardSchema.parse(raw);
    } catch (err) {
      lastErr = err;
      if (attempt === MAX_ATTEMPTS || !shouldRetry(err)) break;
      // Exponential backoff with jitter: 600ms, 1.8s, 5.4s
      const wait = 600 * Math.pow(3, attempt - 1) + Math.floor(Math.random() * 400);
      await sleep(wait);
    }
  }
  throw lastErr;
}
